//user
export const USER_NAME = 'USER_NAME';
export const USER_EMAIL = 'USER_EMAIL';
export const USER_PASSWORD = 'USER_PASSWORD';
export const USER_PHONE = 'USER_PHONE';
export const USER_PROJECTS = 'USER_PROJECTS';
export const USER_SPOTIFY = 'USER_SPOTIFY';
export const USER_INSTAGRAM = 'USER_INSTAGRAM';
export const USER_TIKTOK = 'USER_TIKTOK';
export const USER_FACEBOOK = 'USER_FACEBOOK';
export const USER_YOUTUBE = 'USER_YOUTUBE';
export const USER_WEBSITE = 'USER_WEBSITE';

//project
export const TRACK_DATA = 'TRACK_DATA';
export const SPOTIFY_LINK = 'SPOTIFY_LINK';
export const APPLE_MUSIC_LINK = 'APPLE_MUSIC_LINK';
export const TIKTOK_LINK = 'TIKTOK_LINK';
export const YOUTUBE_LINK = 'YOUTUBE_LINK';
export const INSTAGRAM_LINK = 'INSTAGRAM_LINK';
export const FACEBOOK_LINK = 'FACEBOOK_LINK';
export const SOUNDCLOUD_LINK = 'SOUNDCLOUD_LINK';
export const DEEZER_LINK = 'DEEZER_LINK';
export const WEBSITE_LINK = 'WEBSITE_LINK';
export const TRACK_NAME = 'TRACK_NAME';
export const COVER_IMAGE = 'COVER_IMAGE';
export const ARTISTS = 'ARTISTS';
export const REMOVE_PROJECT = 'REMOVE_PROJECT';

//features
export const OPEN_LOGIN_TOAST = 'OPEN_LOGIN_TOAST';
export const CLOSE_LOGIN_TOAST = 'CLOSE_LOGIN_TOAST';
export const OPEN_SIGN_UP_TOAST = 'OPEN_SIGN_UP_TOAST';
export const CLOSE_SIGN_UP_TOAST = 'CLOSE_SIGN_UP_TOAST';
export const CREATE_NEW_USER = 'CREATE_NEW_USER';
export const TRACK_DATA_LOADING = 'TRACK_DATA_LOADING';
export const REDIRECT = 'REDIRECT';
export const EDIT_USER_INFO = 'EDIT_USER_INFO';

//social
export const FACEBOOK_LOGIN = 'FACEBOOK_LOGIN';
export const GOOGLE_LOGIN = 'GOOGLE_LOGIN';

//errors
export const FACEBOOK_LOGIN_ERROR = 'FACEBOOK_LOGIN_ERROR';
export const USER_NAME_ERROR = 'USER_NAME_ERROR';
export const USER_EMAIL_ERROR = 'USER_EMAIL_ERROR';
export const USER_PASSWORD_ERROR = 'USER_PASSWORD_ERROR';
export const USER_PHONE_ERROR = 'USER_PASSWORD_ERROR';
