//user
export const USER_NAME = 'USER_NAME';
export const USER_EMAIL = 'USER_EMAIL';
export const USER_PASSWORD = 'USER_PASSWORD';
export const USER_PHONE = 'USER_PHONE';

//project
export const SPOTIFY_DATA = 'SPOTIFY_DATA';
export const SPOTIFY_LINK = 'SPOTIFY_LINK';
export const APPLE_MUSIC_LINK = 'APPLE_MUSIC_LINK';
export const TIKTOK_LINK = 'TIKTOK_LINK';
export const YOUTUBE_LINK = 'YOUTUBE_LINK';
export const INSTAGRAM_LINK = 'INSTAGRAM_LINK';
export const FACEBOOK_LINK = 'FACEBOOK_LINK';
export const SOUNDCLOUD_LINK = 'SOUNDCLOUD_LINK';
export const DEEZER_LINK = 'DEEZER_LINK';
export const WEBSITE_LINK = 'WEBSITE_LINK';
export const TRACK_NAME = 'TRACK_NAME';
export const COVER_IMAGE = 'COVER_IMAGE';
export const ARTISTS = 'ARTISTS';

//features
export const OPEN_LOGIN_TOAST = 'OPEN_LOGIN_TOAST';
export const CLOSE_LOGIN_TOAST = 'CLOSE_LOGIN_TOAST';
export const OPEN_SIGN_UP_TOAST = 'OPEN_SIGN_UP_TOAST';
export const CLOSE_SIGN_UP_TOAST = 'CLOSE_SIGN_UP_TOAST';
export const INCREASE_LINK_COUNTER = 'INCREASE_LINK_COUNTER';
export const DECREASE_LINK_COUNTER = 'DECREASE_LINK_COUNTER';
export const CREATE_NEW_USER = 'CREATE_NEW_USER';

//social
export const FACEBOOK_LOGIN = 'FACEBOOK_LOGIN';
export const GOOGLE_LOGIN = 'GOOGLE_LOGIN';

//errors
export const FACEBOOK_LOGIN_ERROR = 'FACEBOOK_LOGIN_ERROR';
export const USER_NAME_ERROR = 'USER_NAME_ERROR';
export const USER_EMAIL_ERROR = 'USER_EMAIL_ERROR';
export const USER_PASSWORD_ERROR = 'USER_PASSWORD_ERROR';
export const USER_PHONE_ERROR = 'USER_PASSWORD_ERROR';
